Repository grafana/helm-charts, pull requests merged in 2022-04, with the labels that each got.

#1130 [loki-distributed] fix: s3 example documentation in README.md
  charts/loki-distributed/Chart.yaml
  charts/loki-distributed/README.md
  charts/loki-distributed/README.md.gotmpl
Labels: documentation

#1233 [mimir-distributed] naginx regex location blocks
  charts/mimir-distributed/Chart.yaml
  charts/mimir-distributed/README.md
  charts/mimir-distributed/values.yaml
Labels: bug

#1228 [enterprise-metrics] Version bump and deprecation in favour of mimir-distributed.
  charts/enterprise-metrics/CHANGELOG.md
  charts/enterprise-metrics/Chart.yaml
  charts/enterprise-metrics/README.md
  charts/enterprise-metrics/values.yaml
Labels: type/docs
